[workspace]
members = [
    "./temis",
    "./samples/counter",
]

resolver = "1"

[workspace.dependencies]
near-abi-client = "0.1.0"

[patch.crates-io]
near-abi-client = { path = "patches/near-abi-client-rs/near-abi-client"}

