[package]
name = "temis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cargo = "0.74.0"
clap = { version = "4.4.7", features = ["derive"] }
jq-rs = { version = "0.4.1", features = ["bundled"] }
near-abi-client = { workspace = true }
